import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowLeft, FileText } from 'lucide-react';
import Logo from '@/components/Logo';

export const metadata: Metadata = {
  title: 'Terms of Service — Dia Chat',
  description: 'Terms and conditions for using Dia Chat.',
};

const sections = [
  {
    title: 'Welcome to Dia Chat',
    body: 'By using Dia Chat, you agree to these terms. Please read them carefully. These terms help us provide a safe, supportive space for everyone.',
  },
  {
    title: 'What Dia Chat Is',
    body: `Dia is an AI-powered companion designed for emotional support, reflection, and casual conversation — a judgment-free space where you can express yourself. Dia is not a replacement for professional mental health care, therapy, or medical advice. If you need professional help, please reach out to a qualified healthcare provider.`,
  },
  {
    title: 'Free to Use',
    body: 'Dia Chat is free. You need a Google account to sign in. No credit card required. No hidden fees. No surprise charges on a Tuesday.',
  },
  {
    title: 'Your Account',
    body: `You're responsible for your account's security. Don't share login credentials. If you notice unauthorised use, revoke access through your Google account settings immediately.`,
  },
  {
    title: 'Acceptable Use',
    body: 'Use Dia Chat respectfully. Don\'t attempt to harm, abuse, or exploit the service; use it for illegal purposes; try to reverse-engineer the AI; or interfere with other users\' experiences.',
  },
  {
    title: 'AI-Generated Content',
    body: `Dia's responses are generated by AI and may not always be accurate or appropriate. AI has limitations — responses may occasionally be incorrect, Dia doesn't have real emotions, and you should not rely on Dia for critical decisions or medical advice. Use your own judgment.`,
  },
  {
    title: 'Privacy & Data',
    body: `Your conversations with Dia are stored locally on your device. Please read our Privacy Policy to understand how we handle your data.`,
    link: { text: 'Read the Privacy Policy →', href: '/privacy' },
  },
  {
    title: 'Service Availability',
    body: `We strive to keep Dia Chat running smoothly, but cannot guarantee 100% uptime. The service may occasionally be unavailable for maintenance or technical reasons. We'll do our best to minimise disruptions.`,
  },
  {
    title: 'Changes to Terms',
    body: `We may update these terms from time to time. Significant changes will be noted by updating the "Last updated" date. Continued use after changes means you accept the new terms.`,
  },
  {
    title: 'Limitation of Liability',
    body: `Dia Chat is provided "as is" without warranties of any kind. We're not liable for damages arising from your use of the service. Use Dia Chat at your own risk and discretion.`,
  },
  {
    title: 'Crisis Resources',
    body: 'If you\'re in crisis or need immediate help, please contact: 988 Suicide & Crisis Lifeline (call or text 988, US), Crisis Text Line (text HOME to 741741), or Emergency Services (911 or your local number).',
  },
  {
    title: 'Contact',
    body: 'Questions about these terms? Visit us on GitHub or at dialabs.tech.',
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#FBF9F4] font-sans">

      {/* Minimal header */}
      <header className="border-b border-[#E5E0D8] bg-[#FBF9F4]/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="max-w-4xl mx-auto px-5 sm:px-8 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2 text-neutral-900 font-bold">
            <Logo className="w-7 h-7 text-primary" />
            <span>Dia Chat</span>
          </Link>
          <Link
            href="/"
            className="flex items-center gap-1.5 text-sm text-neutral-500 hover:text-neutral-900 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to home
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-5 sm:px-8 py-16 sm:py-24">

        {/* Page heading */}
        <div className="mb-14">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-primary/10 border border-primary/20 text-sm font-semibold text-neutral-700 mb-6">
            <FileText className="w-4 h-4 text-primary" />
            Terms of Service
          </div>
          <h1 className="text-4xl sm:text-5xl font-bold text-neutral-900 mb-4 leading-tight">
            Simple terms,<br />
            <span className="italic font-serif font-medium text-neutral-500">no surprises.</span>
          </h1>
          <p className="text-neutral-500 text-base">Last updated: February 10, 2026</p>
        </div>

        {/* Lead paragraph */}
        <p className="text-lg text-neutral-700 leading-relaxed mb-14 border-l-4 border-primary/40 pl-5">
          We want these terms to be readable by a human, not just a lawyer. Below is everything 
          you need to know about using Dia Chat.
        </p>

        {/* Sections */}
        <div className="space-y-12">
          {sections.map((section, i) => (
            <div key={i}>
              <h2 className="text-xl font-bold text-neutral-900 mb-3">{section.title}</h2>
              <p className="text-neutral-600 leading-relaxed">{section.body}</p>
              {section.link && (
                <Link
                  href={section.link.href}
                  className="inline-block mt-3 text-sm font-semibold text-primary hover:underline"
                >
                  {section.link.text}
                </Link>
              )}
              {i < sections.length - 1 && (
                <div className="mt-12 h-px bg-gradient-to-r from-transparent via-[#E5E0D8] to-transparent" />
              )}
            </div>
          ))}
        </div>

        {/* Bottom note */}
        <div className="mt-16 p-6 rounded-2xl bg-primary/8 border border-primary/20">
          <p className="text-sm text-neutral-700 leading-relaxed">
            <strong className="text-neutral-900">Remember:</strong> Dia is here to support you, 
            but it's not a substitute for professional care. Take care of yourself, and don't 
            hesitate to reach out to real people when you need help.
          </p>
        </div>
      </main>

      {/* Footer strip */}
      <footer className="border-t border-[#E5E0D8] py-8 mt-16">
        <div className="max-w-4xl mx-auto px-5 sm:px-8 flex flex-col sm:flex-row items-center justify-between gap-4 text-sm text-neutral-400">
          <p>© {new Date().getFullYear()} DiaLabs. All rights reserved.</p>
          <div className="flex gap-6">
            <Link href="/privacy" className="hover:text-neutral-700 transition-colors">Privacy</Link>
            <a href="https://dialabs.tech" target="_blank" rel="noopener noreferrer" className="hover:text-neutral-700 transition-colors">DiaLabs</a>
          </div>
        </div>
      </footer>
    </div>
  );
}
